config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  before_destroy :destroy_saved_movies

  private

  def destroy_saved_movies
    movies.destroy_all
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  before_destroy :check_for_bookmarks

  private

  def check_for_bookmarks
    return false if bookmarks.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = @list.id
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_bookmarks_path(@bookmark.list), status: :see_other
  end
end

private

def bookmark_params
  params.require(:bookmark).permit(:comment, :movie_id)
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end
end

private

def list_params
  params.require(:list).permit(:name)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a new bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container py-2 my-10">
  <h1>All watchlists created</h1>
  <p>Pick one to see the bookmarks</p>

  <ul>
    <% @lists.each do |list| %>
      <li>
        <%= link_to list.name, list_path(list) %><br>
      </li>
    <% end %>
  </ul>

  <%= link_to "Create a list", new_list_path, class: "btn btn-primary"%>
<div/>

app/views/lists/new.html.erb
<h1>Create a new watchlist</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>


<h3>Movies in this list:</h3>

<% @list.bookmarks.each do |bookmark| %>
  <p><%= bookmark.movie.title %></p>
  <p><%= bookmark.movie.rating %></p>
  <p><%= bookmark.comment %></p>
  <p><%= link_to "Delete a bookmark",
    bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
    class: "btn btn-danger" %></p>
<% end %>

<%= link_to "Create a new bookmark", new_list_bookmark_path(@list), class: "btn btn-primary" %>

<%= link_to "Back to all lists", lists_path, class: "btn btn-secondary" %>